kind: pipeline
type: dcoker
name: default


steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet build
    
- name: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet test