kind: pipeline
type: docker
name: default


steps:
- name : build 
  image: rust
  commands:
    - cargo build


- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 172.27.219.233
    username: vagrant
    password: vagrant
    port: 22
    script:
     - echo lq
     