kind: pipeline
type: docker
name: default


steps:
- name : build 
  image: rust
  commands:
    - cargo build
  volumes:
    - name: data
      path: /home

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 172.27.219.233
    username: vagrant
    password: vagrant
    port: 22
    script:
     - echo lq
     
volumes:
    - name: data
      host:
        path: /home/vagrant/deploy/webserver